// Code generated by protoc-gen-go-connectrpc. DO NOT EDIT.
//
// Source: test.proto

package testprotoconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	testproto "github.com/majst01/go-grpc-net-conn/testproto"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TestServiceName is the fully-qualified name of the TestService service.
	TestServiceName = "testproto.TestService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TestServiceStreamProcedure is the fully-qualified name of the TestService's Stream RPC.
	TestServiceStreamProcedure = "/testproto.TestService/Stream"
)

// TestServiceClient is a client for the testproto.TestService service.
type TestServiceClient interface {
	Stream(context.Context) *connect.BidiStreamForClient[testproto.Bytes, testproto.Bytes]
}

// NewTestServiceClient constructs a client for the testproto.TestService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTestServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TestServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	testServiceMethods := testproto.File_test_proto.Services().ByName("TestService").Methods()
	return &testServiceClient{
		stream: connect.NewClient[testproto.Bytes, testproto.Bytes](
			httpClient,
			baseURL+TestServiceStreamProcedure,
			connect.WithSchema(testServiceMethods.ByName("Stream")),
			connect.WithClientOptions(opts...),
		),
	}
}

// testServiceClient implements TestServiceClient.
type testServiceClient struct {
	stream *connect.Client[testproto.Bytes, testproto.Bytes]
}

// Stream calls testproto.TestService.Stream.
func (c *testServiceClient) Stream(ctx context.Context) *connect.BidiStreamForClient[testproto.Bytes, testproto.Bytes] {
	return c.stream.CallBidiStream(ctx)
}

// TestServiceHandler is an implementation of the testproto.TestService service.
type TestServiceHandler interface {
	Stream(context.Context, *connect.BidiStream[testproto.Bytes, testproto.Bytes]) error
}

// NewTestServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTestServiceHandler(svc TestServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	testServiceMethods := testproto.File_test_proto.Services().ByName("TestService").Methods()
	testServiceStreamHandler := connect.NewBidiStreamHandler(
		TestServiceStreamProcedure,
		svc.Stream,
		connect.WithSchema(testServiceMethods.ByName("Stream")),
		connect.WithHandlerOptions(opts...),
	)
	return "/testproto.TestService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TestServiceStreamProcedure:
			testServiceStreamHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTestServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTestServiceHandler struct{}

func (UnimplementedTestServiceHandler) Stream(context.Context, *connect.BidiStream[testproto.Bytes, testproto.Bytes]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("testproto.TestService.Stream is not implemented"))
}
